# Generated by Django 5.0.1 on 2024-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockage',
            name='media_root',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockage',
            name='media_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
