# Generated by Django 5.0.1 on 2024-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0006_remove_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
