# Generated by Django 5.0.1 on 2024-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0007_userprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
