# Generated by Django 5.0.1 on 2024-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0004_alter_task2_comments_cgartist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
